[mongo]
host = "localhost"
port = 27017
username = "jacksonshinpaugh"
password = "T5yZVLkxm8e9G6Jp"
mongodb_connect = "mongodb+srv://jacksonshinpaugh:T5yZVLkxm8e9G6Jp@datastorage.jf12x0p.mongodb.net/?retryWrites=true&w=majority"